services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: nudgebot
      POSTGRES_USER: nudgebot_user
      POSTGRES_PASSWORD: nudgebot_password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
